{
 "title": "Sine and Cosine Data",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Frame Machine 01",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp_local, sine_data, cosine_data, equipment_id FROM tbl_production WHERE equipment_id = 'Frame Machine 01' ORDER BY timestamp_local ASC "
    }
   ]
  },
  {
   "title": "Filter Insert 01",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT timestamp_local, sine_data, cosine_data, equipment_id FROM tbl_production WHERE equipment_id = 'Filter Insert 01' ORDER BY timestamp_local ASC "
    }
   ]
  },
  {
   "title": "Shrinkwrap 01",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT timestamp_local, sine_data, cosine_data, equipment_id FROM tbl_production WHERE equipment_id = 'Shrink Wrap 01' ORDER BY timestamp_local ASC "
    }
   ]
  }
 ]
}